# Generated by Django 3.2.5 on 2021-07-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0002_borrowlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowlist',
            name='borrowedBookID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
