# Generated by Django 3.2.5 on 2021-07-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0002_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='birthDate',
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(max_length=4),
        ),
    ]
