# Generated by Django 3.2.5 on 2021-07-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0003_auto_20210711_1357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Accountat',
        ),
    ]
