# Generated by Django 3.2.5 on 2021-07-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0003_borrowlist_borrowedbookid'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowlist',
            name='borrowerID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
