# Generated by Django 3.2.5 on 2021-07-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0004_rename_accounts_accountat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accountat',
            new_name='Accounts',
        ),
    ]
