# Generated by Django 3.2.5 on 2021-07-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0005_rename_accountat_accounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='type',
            new_name='accType',
        ),
    ]
